### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by Yarin78** [spotify/postgresql-metrics#7]
We have seen the following exception on a postgres slave machine:

2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net Traceback (most recent call last):
2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net File "/usr/share/python/postgresql-metrics/local/lib/python2.7/site-packages/postgresql_metrics/metrics_logic.py", line 103, in _call_all_db_functions
2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net metrics.extend(db_metrics_func(db_parameter))
2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net File "/usr/share/python/postgresql-metrics/local/lib/python2.7/site-packages/postgresql_metrics/metrics_gatherer.py", line 95, in get_stats_heap_hit_statistics
2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net db_name, heap_read, heap_hit, heap_hit_ratio = get_heap_hit_statistics(db_connection)
2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net File "/usr/share/python/postgresql-metrics/local/lib/python2.7/site-packages/postgresql_metrics/postgres_queries.py", line 159, in get_heap_hit_statistics
2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net recent_heap_hit_ratio = recent_heap_hit / float(recent_heap_hit + recent_heap_read)
2015-11-17T10:33:21.001+00:00 lon2-artifactory4-a2.lon2.spotify.net ZeroDivisionError: float division by zero

**Comment by varjoranta** [comment]
Should be fixed by:
https://github.com/spotify/postgresql-metrics/pull/8

**Comment by mmatalka** [comment]
Merged, thank you for your contribution person I've never met before. :)
